# Generated by Django 2.0 on 2017-12-12 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('companions', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
    ]
