# Generated by Django 2.0.1 on 2018-01-23 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_seen', models.DateTimeField()),
                ('companions', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=215)),
                ('poster_url', models.URLField(default='')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
