# Generated by Django 2.0 on 2018-01-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20171226_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(max_length=220),
        ),
    ]
