# Generated by Django 2.0 on 2018-01-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180102_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(default='Enter what you learned, or what you liked', max_length=220),
        ),
    ]
