# Generated by Django 2.0.1 on 2018-01-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180123_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='user_id',
        ),
    ]
