# Generated by Django 2.0 on 2018-01-03 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180102_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
