# Generated by Django 2.0 on 2018-01-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20180120_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='poster_url',
            field=models.URLField(default=''),
        ),
    ]
