# Generated by Django 2.0 on 2018-01-23 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_seen',
            field=models.DateTimeField(blank=True, default=datetime.date(2018, 1, 22), null=True),
        ),
    ]
