# Generated by Django 2.0 on 2018-01-23 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20180122_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_seen',
            field=models.CharField(default=datetime.date(2018, 1, 22), max_length=100),
        ),
    ]
