# Generated by Django 2.0 on 2018-01-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20180122_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_seen',
            field=models.DateTimeField(),
        ),
    ]
