# Generated by Django 2.0 on 2018-01-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20180122_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
